### PR TITLE
BE global setting

### PR DESCRIPTION
**Pull request by kylung0208**

### CODE REVIEW

**Review by mosano — APPROVED** [review]
thanks for the big help!
now i know how to deal with conflicts in package.json

**Review by ryanycw — APPROVED** [review]
LGTM!

**Comment by Junochiu** [comment]
LGTM, but wonder how we could test it locally?

**Comment by mosano** [comment]
You could test with command:
serverless invoke local --function {function_name}

advanced usage is in docs mentioned at readme.md

**Pull request merged**
